package com.mybatis.generator.mybatis_generator.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_username
     *
     * @mbg.generated
     */
    private String uUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_password
     *
     * @mbg.generated
     */
    private String uPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_username
     *
     * @return the value of users.u_username
     *
     * @mbg.generated
     */
    public String getuUsername() {
        return uUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_username
     *
     * @param uUsername the value for users.u_username
     *
     * @mbg.generated
     */
    public void setuUsername(String uUsername) {
        this.uUsername = uUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_password
     *
     * @return the value of users.u_password
     *
     * @mbg.generated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_password
     *
     * @param uPassword the value for users.u_password
     *
     * @mbg.generated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }
}